/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Codemon_Codemon */

#ifndef _Included_Codemon_Codemon
#define _Included_Codemon_Codemon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Codemon_Codemon
 * Method:    compileToFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Codemon_Codemon_compileToFile
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     Codemon_Codemon
 * Method:    testJni
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_Codemon_Codemon_testJni
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     Codemon_Codemon
 * Method:    selfTestJni
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_Codemon_Codemon_selfTestJni
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     Codemon_Codemon
 * Method:    pvpJni
 * Signature: (ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Codemon_Codemon_pvpJni
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     Codemon_Codemon
 * Method:    reportJni
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Codemon_Codemon_reportJni
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     Codemon_Codemon
 * Method:    compile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Codemon_Codemon_compile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Codemon_Codemon
 * Method:    test
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_Codemon_Codemon_test
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     Codemon_Codemon
 * Method:    selfTest
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_Codemon_Codemon_selfTest
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     Codemon_Codemon
 * Method:    pvp
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Codemon_Codemon_pvp
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     Codemon_Codemon
 * Method:    getReport
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Codemon_Codemon_getReport
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
