/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jniTest */

#ifndef _Included_jniTest
#define _Included_jniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jniTest
 * Method:    compile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jniTest_compile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jniTest
 * Method:    test
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_jniTest_test
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     jniTest
 * Method:    selfTest
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_jniTest_selfTest
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     jniTest
 * Method:    pvp
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jniTest_pvp
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     jniTest
 * Method:    getReport
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jniTest_getReport
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
